services:
  mongodb:
    image: 'mongo'
    container_name: mongodb
    volumes:
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=renan
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    env_file:
      - ./env/mongo.env
    # networks:
    #   - networkName
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: goals-backend
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules 
    env_file: 
      - ./backend/backend.env  
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: goals-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:

